libraries <- function(){

      library(XLConnect)
      library(DataCombine)
      library(psych)
      library(scales)
      library(data.table)
      library(plotly)
      library(choroplethr)
      library(choroplethrMaps)
      library(dplyr)
      library(foreach)
      library(doMC)
      library(snow)
      library(doSNOW)
      registerDoMC(cores=8)
      registerDoSNOW(makeCluster(8, type="SOCK"))
      library(doParallel)
      registerDoParallel(makeCluster(8))
    }